### ISSUE TITLE
'Key not found: completion_ident_query' when using python and lua tree-sitter

### ISSUE THREAD

**Issue by haorenW1025** [vigoux/completion-treesitter#1]
Hey thanks for creating this completion sources:) I've tried it on c and cpp files and looks promising!

However when I try to use other language's tree-sitter I've ran into issue that when starting completion the error message `Key not found: completion_ident_query` will constantly show up.

**Comment by vigoux** [comment]
Yeah, actually that's fine, the only thing we need to work on is to fill `ftplugin/python.vim` with the appropriate variables.

**Comment by vigoux** [comment]
Do you have a sample pyhon source so that I can try and fill the informations we need ?

**Comment by haorenW1025** [comment]
Actually the only things I have is a super simple python file... I think the python files in [autojump](https://github.com/wting/autojump/tree/master/bin) might be useful to check(`autojump_argparse.py` or `autojump_utils.py`).

**Comment by haorenW1025** [comment]
Also can you give a guide on how to appropriate define the variables in `ftplugin/lang.lua`? I want to try some tree-sitter source and maybe I can create some of that and send you a pull request:)

**Comment by vigoux** [comment]
I've added some infos, feel free to look at [this file](https://github.com/vigoux/completion-treesitter/blob/master/after/ftplugin/c.vim) for more informations, and ask your questions here.
The problem is that these variables are really likely to change, but adding new filetypes always helps !

**Comment by vigoux** [comment]
f5b99e8bdb53eababf803864d88f5de5b55ddff0 should have added some basic python filetype, haven't tested it so I can't tell anything about its functionnalites.
Adding new filetypes should normally be far easier.

**Comment by haorenW1025** [comment]
Nice! I'll play around with it in my spare time:) Thanks again!
