### ISSUE TITLE
Is it possible to use it with nvim-compe?

### ISSUE THREAD

**Issue by hrqmonteiro** [vigoux/completion-treesitter#13]
Instead of nvim-completion?

Compe has an option to put "treesitter" as a source of completion:

```
require "compe".setup {
  enabled = true,
  debug = false,
  min_length = 1,
  preselect = "disable",
  source_timeout = 200,
  -- incomplete_delay = 400,
  allow_prefix_unmatch = false,
  documentation = true,
  source = {
    nvim_lsp = {menu = ""},
    nvim_lua = {menu = ""},
    treesitter = {menu = "滑"},
  }
}
```

But i have it enabled in my config, i have your plugin installed, but the treesitter completion never triggers. So i wondered if it was compatible.

**Comment by vigoux** [comment]
Never used nvim-compe, so I can't tell anything.
Maybe you are missing another plugin to interface between the two?
